name: Report Test Results
on:
  workflow_run:
    workflows: [ "CMake" ]
    types: [ completed ]

permissions:
  checks: write

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      # See https://docs.github.com/en/actions/learn-github-actions/variables#default-environment-variables
      # for a list of possible values
      - name: Download Windows Test Report
        uses: dawidd6/action-download-artifact@v6
        with:
          path: Windows
          name: junit-test-results-Windows
          workflow: ${{ github.event.workflow.id }}
          run_id: ${{ github.event.workflow_run.id }}

      - name: Download Linux Test Report
        uses: dawidd6/action-download-artifact@v6
        with:
          path: Linux
          name: junit-test-results-Linux
          workflow: ${{ github.event.workflow.id }}
          run_id: ${{ github.event.workflow_run.id }}

      - name: Download Mac Test Report
        uses: dawidd6/action-download-artifact@v6
        with:
          path: macOS
          name: junit-test-results-macOS
          workflow: ${{ github.event.workflow.id }}
          run_id: ${{ github.event.workflow_run.id }}

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        with:
          commit: ${{github.event.workflow_run.head_sha}}
          report_paths: '**/My Projects/Torque3D/game/test_detail.xml'
